config/routes.rb
Rails.application.routes.draw do

  # get 'static_pages/top'
  # ↑ rails g で最初に作られたroutes ⇒ このままだと、Topページ【/】へアクセスした際、railsのwelcome画面に行ってしまうため、
  # root urlのルーティングを下記に変更
  root 'static_pages#top'
  get '/signup', to: 'users#new'
  
  # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  # resources :users がﾓｰﾀﾞﾙｳｨﾝﾄﾞｳの為👇に変更 9.3
  
  resources :users do
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
    end
    resources :attendances, only: :update # usersリソースのブロック内に記述している 10.5
  end
end

app/models/user.rb
class User < ApplicationRecord  # Userクラスが定義されていること
                                # UserクラスはApplicationRecordクラスを継承していること
                                # この継承の働きによりActive Recordのメソッドが使えると
                                
  # User⇒Attndance=1対多(Attendanceモデルを紐づけ)  10.1.1
  has_many :attendances, dependent: :destroy
  
                                
  # 「remember_token」という仮想の属性を作成します。7.1.2参照
  attr_accessor :remember_token
  
  before_save { self.email = email.downcase } # メールの大文字部分を自動で小文字にするﾒｿｯﾄﾞ
# before_save ﾒｿｯﾄﾞ = オブジェクトが保存される時点で処理を実行
  
  validates :name, presence: true, length: { maximum: 50 }
# presence: trueという引数は1つのハッシュとして考えます 👈少し意味ぷー 4.4より
# 👆 validates(:name, presence: true) と同意 4.4より

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
# 👆mailの正規表現の有効      👆フォーマット
#   正規表現を代入しているVALID_EMAIL_REGEXは、
#   値が変化することがないため定数として定義しています。

  validates :email, presence: true, length: { maximum: 100},
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
                    
  validates :department, length: { in: 2..50 }, allow_blank: true
  
  validates :basic_time, presence: true
  validates :work_time, presence: true
  
  
  has_secure_password  # パスワードをハッシュ化する為のﾒｿｯﾄﾞ ややこしい 4.5参照 
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  # allow_nil: true ⇒ ユーザー編集の際、パスワードが空白でも更新できるようにする！！8.1.4
  # ユーザー新規作成の場合は、has_secure_password が存在性を検証する為OK！！
  
  
    #👇remember_me 機能を実装する為に追加 詳細7.1.1
    
    # 渡された文字列のハッシュ値を返します。
  def User.digest(string)
    cost = 
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返します。
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  # 永続セッションのためハッシュ化したトークンをデータベースに記憶します。
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
    # トークンがダイジェストと一致すればtrueを返します。
  def authenticated?(remember_token)
    # ダイジェストが存在しない場合はfalseを返して終了します。 7.2
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
    # ユーザーのログイン情報を破棄します。7.1.4
    # (remember_me機能により、ログイン状態の永続的保持は出来たが、その影響により、ログアウトが出来なくなっていた。
    #   それを防ぐ為、cookiesを削除する)
    # ⇒方法としては、:remember_digestをnilにする！！
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :set_user, only: [:show, :edit, :update, :destroy]
  # before_action :logged_in_user, only: [:index, :show, :edit, :update, :destroy]
  # before_action :correct_user, only: [:edit, :update]
  # before_action :admin_user, only: :destroy
  # モーダル後👇
  before_action :set_user, only: [:show, :edit, :update, :destroy, :edit_basic_info, :update_basic_info]
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy, :edit_basic_info, :update_basic_info]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: [:destroy, :edit_basic_info, :update_basic_info]
  before_action :set_one_month, only: :show # 10.3 親ｺﾝﾄﾛｰﾗｰであるapplication_controllerに記載
  
  def index
    # @users = User.all  ページネーション機能追加の為下記に変更
    @users = User.paginate(page: params[:page]) # 特殊なpaginateメソッド(あまり説明無) 8.4.2
  end
  
  def show
    # @user = User.find(params[:id]) ⇒ 他のアクションでも実行している為、before_action :set_user にまとめた。
    # debugger # ｲﾝｽﾀﾝｽ変数を定義した直後にこのﾒｿｯﾄﾞが実行されます。
   
    # 👇出勤日数の合計(where.notメソッド) ⇒ 「1ヶ月分の勤怠データの中で、出勤時間が何も無い状態では無いものの数を代入」
    # 10.7
    @worked_sum = @attendances.where.not(started_at: nil).count
  end
  
  def new
    @user = User.new
  end
  
  # ユーザー登録
  
  def create
    # @user = User.new(params[:user]) 現在のrailsのバージョンでは使用出来ない為下記のように記載
    # user_params は private に定義【strong parameters】を使用
    @user = User.new(user_params)
    # @user = User.new(name: params[:name], email: params[:email], image: "default.png", password: params[:password] )
    
    if @user.save
      log_in @user # 保存成功後、ログインします。 log_in メソッド ⇒ session_helperに記載
    # log_in(@user) ⇒ ログインメソッドに@userを引数で渡している
    # log_in(id: 1, name: "第一号", email: "sample@email.com", created_at: "2020-01-10 07:06:42", updated_at: "2020-01-10 07:06:42", password_digest: "$2a$12...")
    
      flash[:success] = "新規作成に成功しました。"
      redirect_to @user
      # redirect_to user_url(@user) 👆railsでは左記のコードのように実行したいことを判断してくれます
    else
      render :new
    end
  end

  def edit
    # @user = User.find(params[:id]) ⇒ 他のアクションでも実行している為、before_action :set_user にまとめた。
  end
  
  def update
    # @user = User.find(params[:id]) ⇒ 他のアクションでも実行している為、before_action :set_user にまとめた。
    if @user.update_attributes(user_params) # データベースの値を複数同時更新 / 更新前にvalidationも実行 (ネットより) ⇒ ｶﾘｷｭﾗﾑには説明ない！！
      flash[:success] = "ユーザー情報を更新しました。"
      redirect_to @user
    else
      render :edit
    end
  end
  
  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to users_url
  end
  
  def edit_basic_info
  end

  def update_basic_info
    if @user.update_attributes(basic_info_params)
      flash[:success] = "#{@user.name}の基本情報を更新しました。"
    else
      flash[:danger] = "#{@user.name}の更新は失敗しました。<br>" + @user.errors.full_messages.join("<br>")
    end
    redirect_to users_url
  end
  
  private # 以下はstrong parameters
  
    def user_params # 5.5.3 参照
      params.require(:user).permit(:name, :email, :department, :password, :password_confirmation)
    end
    
    # 基本情報
    def basic_info_params # 9.3.2 ﾓｰﾀﾞﾙ表示
      params.require(:user).permit(:department, :basic_time, :work_time)
    end
end


# 👇以下は全て attendanceコントローラーでも使う為、親コントローラーであるapplication_controllerへ引越し 11.1.3
  
  
    # # beforeフィルター
    
    
    # # paramsハッシュからユーザーを取得します。
    # def set_user
    #   @user = User.find(params[:id])
    # end
    
    # # ログイン済みのユーザーか確認します。
    # def logged_in_user
    #   unless logged_in?
    #     store_location   
    #   # フレンドリーフォワーディング機能 8.3参照 ※ログインしないで、URL直打ちでeditページ等に
    #   # リクエストした際、そのurlをsessionに保存 (session_helperに定義)
    #     flash[:danger] = "ログインしてください。"
    #     redirect_to login_url
    #   end
    # end
    
    # # アクセスしたユーザーが現在ログインしているユーザーか確認します。
    # def correct_user
    #   @user = User.find(params[:id])
    # # redirect_to(root_url) unless @user == current_user
    # # 上記をより読み手に分かりやすくする為、session_helperにcurrent_user? を定義 8.2.2参照
    #   redirect_to(root_url) unless current_user?(@user) 
    # end
    
    # # システム管理権限所有かどうか判定します。8.5.2
    # def admin_user
    #   redirect_to root_url unless current_user.admin?
    # end

app/helpers/users_helper.rb
module UsersHelper
  
  # 9.2参照
  # 勤怠基本情報を指定のフォーマットで返します。  
  def format_basic_info(time)
    format("%.2f", ((time.hour * 60) + time.min) / 60.0)
  end
end

app/views/users/_edit_basic_info.html.erb
<!--モーダルウィンドウ ※おそらくモーダルはコントローラー不要！？ routes⇒js⇒パーシャル(このファイル)の流れ-->
<% provide(:class_text, 'basic-info') %>
<% provide(:button_text, '更新') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h1 class="modal-title">基本情報編集</h1>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= form_with(model: @user, url: update_basic_info_user_path(@user), local: true, method: :patch) do |f| %>
            <%= render 'shared/error_messages', object: @user %>

            <%= f.label :name, class: "label-#{yield(:class_text)}" %>
            <p><%= @user.name %></p>

            <%= f.label :department, class: "label-#{yield(:class_text)}" %>
            <%= f.text_field :department, class: "form-control" %>

            <%= f.label :basic_time, class: "label-#{yield(:class_text)}" %>
            <%= f.time_field :basic_time, class: "form-control" %>

            <%= f.label :work_time, class: "label-#{yield(:class_text)}" %>
            <%= f.time_field :work_time, class: "form-control" %>

            <div class="center">
              <%= f.submit yield(:button_text), class: "btn btn-primary btn-#{yield(:class_text)}" %>
              <button type="button" class="btn btn-default btn-<%= yield(:class_text) %>" data-dismiss="modal">
                キャンセル
              </button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<!--form_with ⇒ 5.5,8.1参照-->
<%= form_with(model: @user, local: true) do |f| %>
<!--<#%= form_tag users_path do %> 👆の前章【前章ではform_tagを使用】-->
<!--前章では、createアクション(user_path)を指定していたが、-->
<!--form_with はおそらく自動でuserリソースのPOSTリクエストに飛ばしてくれる‼(userﾘｿｰｽのpostはcreateのみ)-->

<!--👆new,editパーシャル化(@user = new ⇒ create , edit ⇒ update)に自動で飛ばす！？ -->


<!--↓パーシャル化したエラーメッセージを表示している-->
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>

<!--  <input class="form-control" type="text" value="テスト太郎" name="user[name]"> 👆の検証 -->
<!--  <input name ="name" value ="<#%= @user.name %>"> 👆の前章 【前章はform_tagを使用】-->

  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class: "form-control" %>
  
  <%= f.label :department, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :department, class: "form-control" %>

  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit") %>
<% provide(:class_text, "user--edit") %>
<% provide(:button_text, "更新") %>
<h1>ユーザー情報の更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
    <!--<#%= form_with(model: @user, local: true) do |f| %>-->
    <!--  <#%= render 'shared/error_messages' %>-->

    <!--  <#%= f.label :name, class: "label-user--edit" %>-->
    <!--  <#%= f.text_field :name, class: "form-control" %>-->

    <!--  <#%= f.label :email, class: "label-user--edit" %>-->
    <!--  <#%= f.email_field :email, class: "form-control" %>-->

    <!--  <#%= f.label :password, class: "label-user--edit" %>-->
    <!--  <#%= f.password_field :password, class: "form-control" %>-->

    <!--  <#%= f.label :password_confirmation, "Confirmation", class: "label-user--edit" %>-->
    <!--  <#%= f.password_field :password_confirmation, class: "form-control" %>-->

    <!--  <#%= f.submit "更新", class: "btn btn-primary btn-block btn-user--edit" %>-->
    <!--<#% end %>-->
  </div>
</div>

app/views/users/edit_basic_info.js.erb
<!--モーダルウインドウ出力するためのJSファイル 9.3.1 -->

$("#edit-basic-info").html("<%= escape_javascript(render 'edit_basic_info') %>");
<!--👆_edit_basic_info.html.erbパーシャルをレンダリング-->
$("#edit-basic-info").modal("show");
<!--モーダルウインドウとして表示を実行-->

app/views/users/index.html.erb
<% provide(:title, 'All Users') %>
<h1>ユーザー一覧</h1>

<div class="col-md-10 col-md-offset-1">
  <%= will_paginate %>
  <table class="table table-condensed table-hover" id="table-users">
    <thead>
      <tr>
        <th><%= User.human_attribute_name :name %></th>
        <!--👆これは何をしてるのか？説明なし 8.4-->
        <!--👇も追加 admin表示とそれ以外の場合 9.3.1 -->
        <th class="center"><%= User.human_attribute_name :department %></th> <!-- 9.3.1 -->
        <% if current_user.admin? %>
          <th class="center"><%= User.human_attribute_name :basic_time %></th> <!-- 9.3.1 -->
          <th class="center"><%= User.human_attribute_name :work_time %></th> <!-- 9.3.1 -->
        <% end %>
        <th></th>
      </tr>
    </thead>

    <% @users.each do |user| %>
      <tr>
        <!--<td>< %= link_to user.name, user %></td> が👇 ※adminの場合はリンク表示、それ以外は通常表示 9.3.1 -->
        <td>
          <% if current_user.admin? %>
            <%= link_to user.name, user %>
          <% else %>
            <%= user.name %>
          <% end %>
        </td>
        <td class="center"><%= user.department.present? ? user.department : "未所属" %></td> <!-- 9.3.1 -->
        <% if current_user.admin? %> <!-- 9.3.1 -->
          <td class="center"><%= format_basic_info(user.basic_time) %></td>
          <td class="center"><%= format_basic_info(user.work_time) %></td>
        <% end %>
        <td class="center"><!-- 9.3.1 -->
          <% if current_user.admin? && !current_user?(user) %>
          <!--👆!current_user?(user)の意味⇒管理者には削除ボタンを表示させないようにしている 8.5.2-->
          <!-- 管理者(current_user) &&(且つ)、 
               each do でそれぞれ表示しようとしてる(user) = current_user?(管理者？) 
               ⇒ true の場合ボタン表示しない (! 否定演算子で) 
               ⇒ false の場合ボタン表示する  (! 否定演算子で) -->
            <%= link_to "基本情報編集", edit_basic_info_user_path(user), remote: true, class: "btn btn-success" %> <!-- 9.3.1 -->
            <%= link_to "削除", user, method: :delete,
                data: { confirm: "削除してよろしいですか？" }, class: "btn btn-danger" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
  <%= will_paginate %>
</div>

<!-- モーダルウィンドウ表示 --> <!-- 9.3.1 -->
<div id="edit-basic-info" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:class_text, 'signup') %>
<!--↑ 8.1.1 参照(パーシャル化し、editと微妙に違うところを、yield に渡してる)-->
<% provide(:button_text, '新規作成') %>
<!--↑ 8.1.1 参照(パーシャル化し、editと微妙に違うところを、yield に渡してる)-->
<h1>ユーザー登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
    <!--👆edit画面とほぼ同じ為、パーシャル化-->
    
    <!--form_with ⇒ 5.5参照-->
<!--    <#%= form_with(model: @user, local: true) do |f| %>-->
<!--<#%= form_tag users_path do %> 👆の前章【前章ではform_tagを使用】-->
<!--前章では、createアクション(user_path)を指定していたが、-->
<!--form_with はおそらく自動でuserリソースのPOSTリクエストに飛ばしてくれる‼(userﾘｿｰｽのpostはcreateのみ)-->
      
      <!--↓パーシャル化したエラーメッセージを表示している-->
<!--      <#%= render 'shared/error_messages' %>-->
      
<!--      <#%= f.label :name, class: "label-signup" %>-->
<!--      <#%= f.text_field :name, class: "form-control" %>-->
      
<!--  <input class="form-control" type="text" value="テスト太郎" name="user[name]"> 👆の検証 -->
<!--  <input name ="name" value ="<#%= @user.name %>"> 👆の前章 【前章はform_tagを使用】-->

      
<!--      <#%= f.label :email, class: "label-signup" %>-->
<!--      <#%= f.email_field :email, class: "form-control" %>-->

<!--      <#%= f.label :password, class: "label-signup" %>-->
<!--      <#%= f.password_field :password, class: "form-control" %>-->

<!--      <#%= f.label :password_confirmation, "Confirmation", class: "label-signup" %>-->
<!--      <#%= f.password_field :password_confirmation, class: "form-control" %>-->

<!--      <#%= f.submit "新規作成", class: "btn btn-primary btn-block btn-signup" %>-->
<!--    <#% end %>-->
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div>
  <table class="table table-bordered table-condensed user-table">
    <!--tr ⇒ 列 td ⇒ セル-->
    <tr> 
      <td>【<%= l(@first_day, format: :middle) %>】勤怠管理表</td>
      <!--👆日付を現在の月表示にしている 10.4で出てきた 10.2見れば分かる-->
      
      <!--下記使い方再考必要‼ 9.2、メモ参照しながら‼-->
      <!--<td>指定勤務時間：< %= @user.work_time %></td> が👇に --> 
      <td>指定勤務時間：<%= format_basic_info(@user.work_time) %></td>
      <!--<td>基本時間：< %= @user.basic_time %></td> が👇に -->
      <td>基本時間：<%= format_basic_info(@user.basic_time) %></td>
      <td>月初日：<%= l(@first_day, format: :short) %></td>
    </tr>

    <tr>
      <td>所属：<%= @user.department.present? ? @user.department : "未所属" %></td>
      <!--👆所属に値がなければ、未所属と表示 9.1.2 より この書き方説明無 -->
      <!--上記のコードが分からなかった為、下記自分で考えた！！下記でも動作した！！-->
      <!--<td>所属：-->
      <!--  < % if @user.department? %>-->
      <!--    < %= @user.department %>-->
      <!--  < % else %>-->
      <!--    < %= "未所属" %>-->
      <!--  < % end %>-->
      <!--</td>-->
      <td>名前：<%= @user.name %></td>
      <td>出勤日数：<%= @worked_sum %></td>
      <td>月末日：<%= l(@last_day, format: :short) %></td>
    </tr>
  </table>
</div>

<!--切替ボタン 10.4-->
<div class="btn-users-show">
  <%= link_to "⇦ 前月へ", user_path(date: @first_day.prev_month), class: "btn btn-info" %>
  <%= link_to "1ヶ月の勤怠編集へ", attendances_edit_one_month_user_path(date: @first_day), class: "btn btn-success" %>
                                                                        <!--↑paramsﾊｯｼｭにdateｷｰとして、@first_dayを渡している(どの月を表示するか判断できる) 11.1.3-->
  <%= link_to "次月へ ⇨", user_path(date: @first_day.next_month), class: "btn btn-info" %>
</div>

<div>
  <table class="table table-bordered table-condensed table-hover" id="table-attendances">
    <thead>
      <tr>
        <th>日付</th>
        <th>曜日</th>
        <th>勤怠登録</th>
        <th>出勤時間</th>
        <th>退勤時間</th>
        <th>在社時間</th>
        <th>備考</th>
      </tr>
    </thead>

    <tbody> 
      <!--< % (@first_day..@last_day).each do |day| %> <!-- 範囲オブジェクト 10.2-->
      <% @attendances.each do |day| %>
        <tr> <!-- 行 -->
          <!--<td>< %= l(day, format: :short) %></td> <!-- 日付表示を2020-01-01から 1/1 にしている 10.2  -->
          <!--10.3により👇に-->
          <td><%= l(day.worked_on, format: :short) %></td>
          
          <!--<td>< %= $days_of_the_week[day.wday] %></td> <!-- 配列のインデックス番号から、曜日を取得している 10.2 説明が少ない!!必要時、落ち着いて考えよう-->
          <!--$days_of_the_week = グローバル変数 10.2 -->
          <!--10.3により👇に-->
          <td><%= $days_of_the_week[day.worked_on.wday] %></td>
          <td>
            <!--実際の日付(パソコンの)と、繰り返し処理中の日付が一致する場合で、且つstarted_atがnilの場合=ボタン表示 10.5.2-->
            <!--< % if (Date.current == day.worked_on) && day.started_at.nil? %>-->
            <!--  < %= link_to "出勤登録", user_attendance_path(@user, day), method: :patch, class: "btn btn-primary btn-attendance" %>-->
            <!--< % elsif (Date.current == day.worked_on) && day.started_at.present? day.finished_at.nil? %>-->
            <!--  < %= link_to "退勤登録", user_attendance_path(@user, day), method: :patch, class: "btn btn-primary btn-attendance" %>-->
            <!--< % end %> -->
            <!--👆が👇へ 10.6.1 ※難しい-->
            <% if btn_text = attendance_state(day) %>
              <%= link_to "#{btn_text}登録", user_attendance_path(@user, day), method: :patch, class: "btn btn-primary btn-attendance" %>
            <% end %>
          </td>
          <!--10.5.3-->
          <td><%= l(day.started_at, format: :time) if day.started_at.present? %></td>
          <td><%= l(day.finished_at, format: :time) if day.finished_at.present? %></td>
          <td>
            <!--在社時間表示 10.8-->
            <% if day.started_at.present? && day.finished_at.present? %>
              <!--< %= working_times(day.started_at, day.finished_at) %>-->
            <!--10.9.2より👇へ-->
              <%= str_times = working_times(day.started_at, day.finished_at) %>
              <% @total_working_times = @total_working_times.to_f + str_times.to_f %>
              <!--↑理解していない↑ 変数を定義して(@total_working_times) すぐにその変数を使用して計算している-->
            <% end %>
          </td>
          <td><%= day.note %></td> <!-- 11.3.2 -->
        </tr>
      <% end %>
    </tbody>
    
    <tfoot>
      <!--rowspan:縦結合、colspan：横結合-->
      <tr>
        <td colspan="2">累計日数</td>
        <td colspan="2">総合勤務時間</td>
        <td colspan="2">累計在社時間</td>
        <td rowspan="2"></td>
      </tr>
      <tr>
        <!--累計日数-->
        <td colspan="2"><%= @attendances.count %></td>
        <!--総合勤務日数(指定勤務時間 × 出勤日数)-->
        <td colspan="2"><%= format_basic_info(@user.work_time).to_f * @worked_sum %></td>
        <!--累計在社時間-->
        <td colspan="2"><%= format("%.2f", @total_working_times.to_f) %></td>
      </tr>
    </tfoot>    
  </table>
</div>