config/routes.rb
Rails.application.routes.draw do

  # get 'static_pages/top'
  # ↑ rails g で最初に作られたroutes ⇒ このままだと、Topページ【/】へアクセスした際、railsのwelcome画面に行ってしまうため、
  # root urlのルーティングを下記に変更
  root 'static_pages#top'
  get '/signup', to: 'users#new'
  
  # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  # resources :users がﾓｰﾀﾞﾙｳｨﾝﾄﾞｳの為👇に変更 9.3
  
  resources :users do
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
    end
    resources :attendances, only: :update # usersリソースのブロック内に記述している 10.5
  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Attendance App", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "ホーム", root_path %></li>
        <% if logged_in? %>
          <li><%= link_to "全てのユーザー", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              メニュー <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "勤怠", current_user %></li>
          <!--👆ﾙｰﾃｨﾝｸﾞﾍﾙﾊﾟｰ省略形 ※ current_userは１つのユーザーオブジェクトである為、-->
          <!--<li><#%= link_to "Show", user_path(current_user) %></li>-->
          <!--  Railsが上記のコードを実行したいと判断 6.4-->
              <li><%= link_to "設定", edit_user_path(current_user) %></li>
          <!--edit_user_path(current_user) ⇒ Railsは現在ログイン中のユーザーIDをリソースに当てはめて判断します 8.1参照-->
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "ログイン", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title> <!-- yield ⇒ 産出する -->
                <!--↑full_titleﾒｿｯﾄﾞ⇒自分で作成したﾒｿｯﾄﾞを使用している-->
                <!--↑ﾒｿｯﾄﾞは、application_helperに記載-->
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
  <%= render 'layouts/shim' %>
  </head>
  <body>
    <!--<header class="navbar navbar-fixed-top navbar-inverse">-->
    <!--  <div class="container">-->
    <!--    <#%= link_to "Attendance App", '#', id: "logo" %>-->
    <!--    <nav>-->
    <!--      <ul class="nav navbar-nav navbar-right">-->
    <!--        <li><#%= link_to "Top",   '#' %></li>-->
    <!--        <li><#%= link_to "Log in", '#' %></li>-->
    <!--      </ul>-->
    <!--    </nav>-->
    <!--  </div>-->
    <!--</header>-->
    <!-- 上のheaderの内容が下のこの1行で収まる(パーシャル化している) -->
    <%= render 'layouts/header' %>
    <div class="container">
      
      <!--サクセスメッセージ等の表示【5.5.6】-->
      <% flash.each do |message_type, msg| %>
        <!--<div class="alert alert-< %= message_type %>">< %= msg %></div> これが👇.html_sage 追加 9.3.2-->
        <div class="alert alert-<%= message_type %>"><%= msg.html_safe %></div>
      <% end %>
      <%= yield %>
      
      <!--↓デバッグを表示する/if は開発環境【development】のみで表示-->
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>